---

- hosts: all
  become: true
  pre_tasks:

  - name: UPDATE Ubuntu
    tags: update
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: Install Easy-RSA and OpenSSL for CA
    apt:
      name:
        - easy-rsa
        - openssl

- hosts: Control_servers
  become: true
  tasks:

  - name: Copy
    run_once: yes
    fetch: src=/tmp/ca.crt dest=CAfiles/ flat=yes
    when: inventory_hostname == "192.168.56.105"

- hosts: Manage_servers
  become: true
  tasks:

  - name: Output
    copy: src=CAfiles/ca.crt dest=~/cpe243ansible/
    when: inventory_hostname == "192.168.56.106"
